# Generated by Django 6.0.6 on 2026-10-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_app', '0002_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
